# Generated by Django 3.0.7 on 2020-08-10 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Adds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=50)),
                ('banner', models.ImageField(upload_to='Adds/banner')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('payment', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adds.Category')),
                ('positions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adds.Position')),
            ],
        ),
    ]
