# Generated by Django 3.0.7 on 2020-07-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shop_address',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='order',
            name='shop_pincode',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='u_delivery_address',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='order',
            name='u_delivery_note',
            field=models.CharField(max_length=300),
        ),
    ]
