# Generated by Django 3.0.7 on 2020-07-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200716_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='u_delivery_note',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
