# Generated by Django 3.0.7 on 2020-07-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200716_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_staff',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
